site_name: ML
theme: 
  name: material
  features:
    - search.suggest
    - search.highlight
    - navigation.tabs
    - toc.float

  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: magenta
      accent: pink
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to Light Mode
      primary: magenta
      accent: lime

  icon:
    repo: fontawesome/brands/github
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

nav:
  - Home : "index.md"
  - Machine Learning:
    - Machine Learning Theory:
      - PCA:
        - Principal Component Analysis (PCA): "PCA/Representation Learning.md"

    
# REPO CONFIG
repo_url : "https://github.com/shreyanshhub/machine_learning_"
repo_name : "shreyanshhub/machine_learning_"



# EXTENSIONS AND CSS
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css
